### PR TITLE
fixed minor native bugs

### LINKED ISSUE #56: Cannot read property 'subscribers' of undefined
Getting the error - "Cannot read property 'subscribers' of undefined"

### PR DESCRIPTION
**Pull request by filbertteo**
This PR addresses 2 main issues:
1. The `loop` function in `src/native/utils/game-loop.js` has been changed from arrow function to regular function, but `this` is not bound to the function, resulting in issue https://github.com/FormidableLabs/react-game-kit/issues/56.
2. The `unsubscribe` function in `src/native/utils/game-loop.js` currently uses `splice` instead of `delete`. This causes an app crash, for example when a subscriber in the middle of the array gets removed before another subscriber at the end of the array, as the ID returned during subscription will no longer be valid, and so the callback will not get removed.

-----

Closes #56

### CODE REVIEW

File: src/native/utils/game-loop.js [hunk 1]
```diff
@@ -22,7 +23,7 @@ export default class GameLoop {
   }
 
   unsubscribe(id) {
-    this.subscribers.splice((id - 1), 1);
+    delete this.subscribers[id - 1];
```
Comment (ryan-roemer) [inline src/native/utils/game-loop.js]: This change will mean that for something like:

```js
subscribers = [1, 2, 3]
```

If removing `id = 2` we'd end up with:

```js
[1, 3]
````

but now would instead get:

```js
[1, empty, 3]
```

@kenwheeler -- Does the above change look ok?

Comment (kenwheeler) [reply src/native/utils/game-loop.js]: 👍

**Comment by ryan-roemer** [comment]
Thanks @filbertteo ! Released in `react-game-kit@1.0.6`
